TAG_MAP = {
    # --- Major Genres (주요 장르) ---
    "판타지": "Fantasy",
    "현대": "Modern",
    "현대판타지": "Modern Fantasy",
    "로맨스": "Romance",
    "로맨스판타지": "Romance Fantasy",
    "무협": "Martial Arts",
    "라이트노벨": "Light Novel",
    "일상": "Slice of Life",
    "코미디": "Comedy",
    "드라마": "Drama",
    "스릴러": "Thriller",
    "공포": "Horror",
    "SF": "Sci-Fi",
    "미스터리": "Mystery",
    "어반판타지": "Urban Fantasy",
    "대체역사": "Alternate History",
    "정통판타지": "High Fantasy",
    "퓨전무협": "Fusion Martial Arts",
    "선협": "Xianxia",
    "무림": "Murim",
    "퓨전": "Fusion",

    # --- Core Tropes & Systems (주요 요소 및 시스템) ---
    "먼치킨": "Overpowered (OP)",
    "조건부먼치킨": "Conditional OP",
    "성장형먼치킨": "Growth-type OP",
    "약먼치킨": "Weak-to-Strong OP",
    "집착": "Obsession",
    "순애": "Pure Love",
    "하렘": "Harem",
    "착각": "Misunderstanding",
    "착각계": "Misunderstanding Style",
    "전생": "Reincarnation",
    "빙의": "Possession",
    "게임빙의": "Game Possession",
    "회귀": "Regression",
    "무한회귀": "Infinite Regression",
    "환생": "Rebirth",
    "피폐": "Angst/Depravity",
    "약피폐": "Light Angst",
    "초반피폐": "Early Angst",
    "성장": "Growth",
    "성장형": "Slow Growth",
    "육성": "Nurturing",
    "후회": "Regret",
    "약후회": "Light Regret",
    "구원": "Salvation",
    "치유": "Healing",
    "복수": "Revenge",
    "아카데미": "Academy",
    "학원": "Academy",
    "학원물": "Academy Life",
    "캠퍼스": "Campus",
    "헌터": "Hunter",
    "게임": "Game",
    "가상현실게임": "VR Game",
    "게임판타지": "Game Fantasy",
    "시스템": "System",
    "상태창": "Status Window",
    "퀘스트": "Quest",
    "인외": "Non-Human",
    "이종족": "Demi-human",
    "아포칼립스": "Apocalypse",
    "포스트아포칼립스": "Post-Apocalypse",
    "TS": "Gender Bender",
    "TS히로인": "GB Heroine",
    "일부TS": "Partial TS",
    "찐TS물": "Real TS",
    "암타": "Female Depravity (TS)",
    "백합": "Yuri (GL)",
    "약백합": "Light Yuri",
    "GL": "Girls Love",
    "노맨스": "No Romance",
    "남성향": "Male Oriented",
    "여주인공": "Female Protagonist",
    "남주인공": "Male Protagonist",
    "얀데레": "Yandere",
    "나데나데": "Pampering",
    "인터넷방송": "Streaming/Broadcasting",
    "커뮤니티": "Community",
    "갤러리": "Gallery/Forum",
    "사이다": "Refreshing (OP/Fast-paced)",
    "전문직": "Professional",
    "경영": "Management",
    "영지": "Territory/Lord",
    "정치": "Politics",
    "재벌": "Chaebol/Tycoon",
    "천재": "Genius",
    "둔재": "Dullard",
    "빌런": "Villain",
    "악당": "Villain",
    "악역": "Antagonist",
    "악역영애": "Villainess",
    "히어로": "Hero",
    "다크히어로": "Dark Hero",
    "괴담": "Urban Legend",
    "괴이": "Anomaly",
    "이상현상": "Phenomenon",
    "생존": "Survival",
    "던전": "Dungeon",
    "미궁": "Labyrinth",
    "탑": "Tower",
    "탑등반": "Tower Climbing",
    "게이트": "Gate",
    "성좌": "Constellation",
    "갑질": "Power Trip",
    "착각": "Misunderstanding",
    "오해": "Misunderstanding",
    "힐링": "Healing",
    "일상": "Slice of Life",
    "슬로우라이프": "Slow Life",
    "옴니버스": "Omnibus",

    # --- Fandoms & Series (패러디 및 시리즈) ---
    "패러디": "Parody/Fanfic",
    "2차창작": "Secondary Creation",
    "블루아카이브": "Blue Archive", "블루아카": "Blue Archive", "블아": "Blue Archive",
    "프문": "Project Moon", "프로젝트문": "Project Moon", "림버스": "Limbus Company", "림컴": "Limbus Company",
    "라오루": "Library of Ruina", "로보토미": "Lobotomy Corp",
    "원신": "Genshin Impact",
    "스타레일": "Honkai: Star Rail", "붕스": "Honkai: Star Rail", "붕괴스타레일": "Honkai: Star Rail",
    "붕괴": "Honkai", "붕괴3rd": "Honkai Impact 3rd",
    "FATE": "Fate Series", "페이트": "Fate Series", "FGO": "Fate/Grand Order", "페그오": "Fate/Grand Order",
    "포켓몬": "Pokemon", "주술회전": "Jujutsu Kaisen",
    "전독시": "ORV (Omniscient Reader)", "전지적독자시점": "Omniscient Reader",
    "원피스": "One Piece", "나히아": "My Hero Academia", "히로아카": "My Hero Academia",
    "니케": "NIKKE", "승리의여신": "NIKKE",
    "코노스바": "Konosuba", "해리포터": "Harry Potter", "워해머": "Warhammer", "워해머40K": "Warhammer 40K",
    "데어라": "Date A Live", "블리치": "Bleach", "울트라킬": "ULTRAKILL", "유희왕": "Yu-Gi-Oh!",
    "귀멸의칼날": "Demon Slayer", "귀칼": "Demon Slayer", "체인소맨": "Chainsaw Man", "나루토": "Naruto",
    "던만추": "Danmachi", "갓오브하이스쿨": "God of Highschool", "갓오하": "God of Highschool",
    "가면라이더": "Kamen Rider", "슈퍼전대": "Super Sentai", "버튜버": "VTuber", "이세계아이돌": "Isekai Idol",
    "명일방주": "Arknights", "소녀전선": "Girls' Frontline", "홀로라이브": "Hololive", "스텔라이브": "StelLive",
    "죠죠": "JoJo", "하이스쿨DXD": "High School DxD", "코드기어스": "Code Geass", "소아온": "SAO",
    "토리코": "Toriko", "슬라임": "Tensura", "할로우나이트": "Hollow Knight", "도쿄구울": "Tokyo Ghoul",
    "메이플스토리": "MapleStory", "메이플": "MapleStory", "오버로드": "Overlord", "화산귀환": "Mount Hua Sect",
    "우마무스메": "Uma Musume", "젠존제": "ZZZ", "젠레스존제로": "Zenless Zone Zero", "ZZZ": "Zenless Zone Zero",
    "명조": "Wuthering Waves", "트릭컬": "Trickcal", "나혼렙": "Solo Leveling", "최애의아이": "Oshi no Ko",
    "블랙코미디": "Black Comedy", "엘든링": "Elden Ring", "페어리테일": "Fairy Tail", "동방프로젝트": "Touhou", "동방": "Touhou",

    # --- NSFW & Adult (성인용 및 매니악 태그) ---
    "19금": "R-18",
    "성인": "Adult",
    "고수위": "High-Heat/Explicit",
    "야설": "Erotica",
    "조교": "Training/Conditioning",
    "능욕": "Humiliation",
    "타락": "Corruption",
    "암컷타락": "Feminization/Corruption",
    "강제암컷타락": "Forced Feminization",
    "최면": "Hypnosis",
    "관음": "Voyeurism",
    "절륜": "High Stamina/Vigor",
    "NTR": "NTR (Cuckoldry)",
    "NTL": "NTL (Stealing)",
    "약NTR": "Light NTR",
    "NTS": "NTS (Anti-NTR/Pure)",
    "역강간": "Reverse Rape",
    "남녀역전": "Gender Role Reversal",
    "정조역전": "Reversed Virginity World",
    "펨돔": "Femdom",
    "소프트펨돔": "Soft Femdom",
    "여공남수": "Femdom",
    "후타나리": "Futanari",
    "촉수": "Tentacles",
    "근친": "Incest",
    "유사근친": "Pseudo-incest",
    "모녀": "Mother & Daughter",
    "유부녀": "Married Woman",
    "밀프": "MILF",
    "쇼타": "Shota",
    "오네쇼타": "Onee-Shota",
    "보추": "Femboy",
    "오토코노코": "Trap/Femboy",
    "감금": "Confinement",
    "노예": "Slave",
    "세뇌": "Brainwashing",
    "가스라이팅": "Gaslighting",
    "의존": "Dependency",
    "상식개변": "Common Sense Alteration",
    "성접대": "Sexual Service",
    "노출": "Exposure",
    "애널": "Anal",
    "착정": "Milking",
    "폭유": "Huge Breasts",
    "임신": "Pregnancy",
    "모유": "Lactation",
    "수간": "Bestiality",
    "MC물": "Mind Control",
    "이상성욕": "Fetish",
    "하드코어": "Hardcore",
    "천박": "Vulgar",
    "복종": "Obedience",

    # --- Others (기타 및 세부 장르) ---
    "중세": "Medieval",
    "다중": "Multiple POV",
    "유희생활": "Playful Life",
    "액션": "Action",
    "이세계": "Isekai",
    "생존": "Survival",
    "로또": "Lottery",
    "요리": "Cooking",
    "스포츠": "Sports",
    "축구": "Soccer",
    "야구": "Baseball",
    "군대": "Military",
    "밀리터리": "Military",
    "전쟁": "War",
    "역사": "History",
    "근대": "Modern Era",
    "근현대": "Contemporary",
    "동양풍": "Eastern Style",
    "무공": "Martial Arts",
    "신화": "Mythology",
    "초능력": "Superpower",
    "이능력": "Special Ability",
    "마법": "Magic",
    "마법사": "Mage/Wizard",
    "마법소녀": "Magical Girl",
    "연예인": "Celebrity",
    "아이돌": "Idol",
    "지름작": "Impulsive Writing",
    "리메이크": "Remake",
    "설붕": "Setting Inconsistency",
    "캐붕": "Character Inconsistency",
    "기타": "Etc",
    # --- Fandoms & Specific Series ---
    "림버스컴퍼니": "Limbus Company",
    "포켓몬스터": "Pokemon",
    "터닝메카드": "Turning Mecard",
    "나이트런": "Night Run",
    "붕괴3RD": "Honkai Impact 3rd",
    "봇치더락": "Bocchi the Rock",
    "데이트어라이브": "Date A Live",
    "벽람항로": "Azur Lane",
    "마블": "Marvel",
    "유유백서": "YuYu Hakusho",
    "해즈빈": "Hazbin Hotel",
    "헬루바보스": "Helluva Boss",
    "에반게리온": "Evangelion",
    "명방": "Arknights",
    "쿠키런": "Cookie Run",
    "워크래프트3": "Warcraft 3",
    "WOW": "World of Warcraft",

    # --- Tropes & Settings ---
    "다크판타지": "Dark Fantasy",
    "독참소": "Reader Participation",
    "캣파이트": "Catfight",
    "원작파괴": "Original Plot Destruction",
    "사이버펑크": "Cyberpunk",
    "삼국지": "Three Kingdoms",
    "소꿉친구": "Childhood Friend",
    "피카레스크": "Picaresque",
    "몬무스": "Monster Girl",
    "병약": "Sickly/Weak Body",
    "탑등반물": "Tower Climbing",
    "기억상실": "Amnesia",
    "이세계전이": "Isekai Transfer",
    "고인물": "Veteran/Pro Player",
    "이종간": "Interspecies",
    "츤데레": "Tsundere",
    "메이드": "Maid",
    "성비불균형": "Gender Ratio Imbalance",
    "남존여비": "Male Superiority",
    "여존남비": "Female Superiority",

    # --- Gameplay & System ---
    "가챠": "Gacha",
    "먹방": "Mukbang/Eating Show",
    "코인": "Coin/Crypto",
    "투자": "Investment",
    "쌀먹": "RMT (Real Money Trading)",
    "기반": "Based on (OC/Setting)",

    # --- Character Types ---
    "연예계": "Entertainment Industry",
    "마왕": "Demon Lord",
    "성녀": "Saintess",
    "용사": "Hero/Braver",
    "네크로맨서": "Necromancer",
    "대장장이": "Blacksmith",
    "교수": "Professor",
    "매니저": "Manager",
    "양아들": "Adopted Son",
    "새엄마": "Stepmother"
}

def translate_tags(tag_string):
    """Translates a comma-separated string of Korean tags to English."""
    if not tag_string:
        return ""
    tags = tag_string.split(',')
    # Use the map, fallback to original tag if translation is missing
    translated = [TAG_MAP.get(t.strip(), t.strip()) for t in tags if t.strip()]
    return ", ".join(translated)
